openapi: 3.2.0
info:
  title: scaffolder Templating Extensions API
  version: '1'
  description: The Backstage backend plugin that helps you create new things
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact: {}
servers:
- url: /
tags:
- name: Templating Extensions
paths:
  /v2/templating-extensions:
    get:
      operationId: ListTemplatingExtensions
      description: Returns a structure describing the available templating extensions.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTemplatingExtensionsResponse'
      security:
      - {}
      - JWT: []
      parameters: []
      tags:
      - Templating Extensions
      summary: List templating extensions
      x-summary-source: derived
components:
  schemas:
    TemplateFilter:
      type: object
      properties:
        description:
          type: string
        schema:
          type: object
          properties:
            input:
              $ref: '#/components/schemas/JsonObject'
            arguments:
              type: array
              items:
                $ref: '#/components/schemas/JsonObject'
            output:
              $ref: '#/components/schemas/JsonObject'
        examples:
          type: array
          items:
            $ref: '#/components/schemas/ScaffolderUsageExample'
      description: The response shape for a single filter in the `listTemplatingExtensions` call to the `scaffolder-backend`
    TemplateGlobalValue:
      type: object
      properties:
        description:
          type: string
        value:
          anyOf:
          - type: object
          - type: 'null'
      required:
      - value
      description: The response shape for a single global value in the `listTemplatingExtensions` call to the `scaffolder-backend`
    JsonObject:
      type: object
      properties: {}
      description: A type representing all allowed JSON object values.
      additionalProperties: {}
    TemplateGlobalFunction:
      type: object
      properties:
        description:
          type: string
        schema:
          type: object
          properties:
            arguments:
              type: array
              items:
                $ref: '#/components/schemas/JsonObject'
            output:
              $ref: '#/components/schemas/JsonObject'
        examples:
          type: array
          items:
            $ref: '#/components/schemas/ScaffolderUsageExample'
      description: The response shape for a single global function in the `listTemplatingExtensions` call to the `scaffolder-backend`
    ScaffolderUsageExample:
      type: object
      properties:
        description:
          type: string
        example:
          type: string
        notes:
          type: string
      required:
      - example
      description: A single scaffolder usage example
    ListTemplatingExtensionsResponse:
      type: object
      properties:
        filters:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TemplateFilter'
        globals:
          type: object
          properties:
            functions:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/TemplateGlobalFunction'
            values:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/TemplateGlobalValue'
          required:
          - functions
          - values
      required:
      - filters
      - globals
      description: The response shape for the `listTemplatingExtensions` call to the `scaffolder-backend`
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
