openapi: 3.2.0
info:
  title: scaffolder Autocomplete API
  version: '1'
  description: The Backstage backend plugin that helps you create new things
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact: {}
servers:
- url: /
tags:
- name: Autocomplete
paths:
  /v2/autocomplete/{provider}/{resource}:
    post:
      operationId: Autocomplete
      description: Perform an autocomplete for the given provider and resource.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  type: object
                  additionalProperties:
                    type: string
                token:
                  type: string
              required:
              - context
              - token
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        id:
                          type: string
                      required:
                      - id
                required:
                - results
        '400':
          description: Unsupported provider.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  name:
                    type: string
      parameters:
      - in: path
        name: provider
        required: true
        schema:
          type: string
      - in: path
        name: resource
        required: true
        schema:
          type: string
      tags:
      - Autocomplete
      summary: Autocomplete
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
